### ISSUE TITLE
Error on build for iOS

### ISSUE THREAD

**Issue by Batres35** [tcronis/url_audio_stream#1]
When i try to compile the proyect, it gives me this error:

> Launching lib/main.dart on iPhone de Batres in debug mode...
> Automatically signing iOS for device deployment using specified development team in Xcode project: FFFFFFFFFF
> CocoaPods' output:
> ↳
>       Preparing
>     Analyzing dependencies
>     Inspecting targets to integrate
>       Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
>     Finding Podfile changes
>       A url_audio_stream
>       R flutter_radio
>       - Flutter
>       - url_launcher
>     Fetching external sources
>     -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
>     -> Fetching podspec for `url_audio_stream` from `.symlinks/plugins/url_audio_stream/ios`
>     -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`
>     Resolving dependencies of `Podfile`
>       CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
>     Comparing resolved specification to the sandbox manifest
>       A Flutter
>       A url_audio_stream
>       A url_launcher
>     Downloading dependencies
>     -> Installing Flutter (1.0.0)
>     -> Installing url_audio_stream (0.0.1)
>     -> Installing url_launcher (0.0.1)
>       - Running pre install hooks
>     [!] Unable to determine Swift version for the following pods:
> - `url_audio_stream` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/target_validator.rb:125:in `verify_swift_pods_swift_version'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/target_validator.rb:39:in `validate!'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:590:in `validate_targets'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:158:in `install!'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
>     /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
>     /usr/local/bin/pod:23:in `load'
>     /usr/local/bin/pod:23:in `<main>'
> Error output from CocoaPods:
> ↳
>         WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
>         Consider adding the following to ~/.profile:
>         export LANG=en_US.UTF-8
>         
>     [!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
> Error running pod install
> Exited (sigterm)

Any help?

**Comment by tcronis** [comment]
Have you set your Podfile to a swift version? It looks like that is a common issue with Flutter/Dart plugins, I have seen it a few times on other plugin's GitHubs. Check out this [url](https://stackoverflow.com/questions/50458556/flutter-swift-version-must-be-set-to-a-supported-value) that discusses it, keep in mind this is designed on Swift 5 as well. If you haven't tried this before, try putting this in your Podfile: 

```
target 'Runner' do
  use_frameworks! 
  ...
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0' 
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

**Comment by Batres35** [comment]
I have been set te changes on de "Podfile", that is how it looks now:

> # Uncomment this line to define a global platform for your project
> # platform :ios, '9.0'
> 
> # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
> ENV['COCOAPODS_DISABLE_STATS'] = 'true'
> 
> project 'Runner', {
>   'Debug' => :debug,
>   'Profile' => :release,
>   'Release' => :release,
> }
> 
> def parse_KV_file(file, separator='=')
>   file_abs_path = File.expand_path(file)
>   if !File.exists? file_abs_path
>     return [];
>   end
>   pods_ary = []
>   skip_line_start_symbols = ["#", "/"]
>   File.foreach(file_abs_path) { |line|
>       next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
>       plugin = line.split(pattern=separator)
>       if plugin.length == 2
>         podname = plugin[0].strip()
>         path = plugin[1].strip()
>         podpath = File.expand_path("#{path}", file_abs_path)
>         pods_ary.push({:name => podname, :path => podpath});
>       else
>         puts "Invalid plugin specification: #{line}"
>       end
>   }
>   return pods_ary
> end
> 
> target 'Runner' do
>   use_frameworks!  # required by simple_permission
>   # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
>   # referring to absolute paths on developers' machines.
>   system('rm -rf .symlinks')
>   system('mkdir -p .symlinks/plugins')
> 
>   # Flutter Pods
>   generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
>   if generated_xcode_build_settings.empty?
>     puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first."
>   end
>   generated_xcode_build_settings.map { |p|
>     if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
>       symlink = File.join('.symlinks', 'flutter')
>       File.symlink(File.dirname(p[:path]), symlink)
>       pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
>     end
>   }
> 
>   # Plugin Pods
>   plugin_pods = parse_KV_file('../.flutter-plugins')
>   plugin_pods.map { |p|
>     symlink = File.join('.symlinks', 'plugins', p[:name])
>     File.symlink(p[:path], symlink)
>     pod p[:name], :path => File.join(symlink, 'ios')
>   }
> end
> 
> # Prevent Cocoapods from embedding a second Flutter framework and causing an error with the new Xcode build system.
> install! 'cocoapods', :disable_input_output_paths => true
> 
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     target.build_configurations.each do |config|
>       config.build_settings['SWIFT_VERSION'] = '5.0'  # required by simple_permission
>       config.build_settings['ENABLE_BITCODE'] = 'NO'
>     end
>   end
> end

But i'm still with the same issue

> [!] Unable to determine Swift version for the following pods:
> 
> - `url_audio_stream` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
> 
> [!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by Batres35** [comment]
> Have you set your Podfile to a swift version? It looks like that is a common issue with Flutter/Dart plugins, I have seen it a few times on other plugin's GitHubs. Check out this [url](https://stackoverflow.com/questions/50458556/flutter-swift-version-must-be-set-to-a-supported-value) that discusses it, keep in mind this is designed on Swift 5 as well. If you haven't tried this before, try putting this in your Podfile:
> 
> ```
> target 'Runner' do
>   use_frameworks! 
>   ...
> end
> 
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     target.build_configurations.each do |config|
>       config.build_settings['SWIFT_VERSION'] = '5.0' 
>       config.build_settings['ENABLE_BITCODE'] = 'NO'
>     end
>   end
> end
> ```

I did what you tell me and then this
[https://github.com/kiwi-bop/flutter_crashlytics/issues/22#issuecomment-457580840](url)
to solve the problem with swift, now it compiles right! Thanks
