### ISSUE TITLE
Plugin doesn't play a stream audio on a real iPhone

### ISSUE THREAD

**Issue by Batres35** [tcronis/url_audio_stream#2]
I tested the plugin with a stream audio on an iPhone Simulator with iOS 13.1 and it works great and the audio plays, but when i try to use the same app on a real iPhone it simply dont play the audio.

What am i doing wrong?

**Comment by tcronis** [comment]
Interesting, I'm glad you figured out the issue from earlier. What iOS are you running on the iPhone, 13.1? I've tried it on my phone, which is running 13 and it works.

**Comment by Batres35** [comment]
> Interesting, I'm glad you figured out the issue from earlier. What iOS are you running on the iPhone, 13.1? I've tried it on my phone, which is running 13 and it works.

The real iPhone uses the same iOS than the simulator, 13.1.

**Comment by tcronis** [comment]
If you're running it live on the iPhone (in debugger mode), what is flutter's output in the console? I am running 13.1.2 and it builds fine without any errors.

**Comment by Batres35** [comment]
I don't have any errors too, but it still without sound.

> Launching lib/main.dart on iPhone in debug mode...
> Automatically signing iOS for device deployment using specified development team in Xcode project: XXXXXXXXXX
> Xcode build done.                                           52.1s
> Checking for advertised Dart observatories...
> Checking for available port on com.project.project._dartobservatory._tcp.local
> Checking for authentication code for com.project.project._dartobservatory._tcp.local

This is the code that i'm using on the bloc for handle the audio.

`import 'package:rxdart/rxdart.dart';
import 'package:url_audio_stream/url_audio_stream.dart';

class PlayerBloc {
  bool isPlaying = false;
  AudioStream stream;
  String urlStream;

  final playerStatus = new BehaviorSubject<bool>();

  Observable<bool> get playerStatusObservable => playerStatus.stream;

  PlayerBloc(String urlStream) {
    this.urlStream = urlStream;
    this.stream = new AudioStream(this.urlStream);
  }

  sinkPlayerStatus() {
    try {
      playerStatus.add(isPlaying);
    } catch (err) {
      throw Exception(err);
    }
  }

  start() {
    try {
      stream.start();
      isPlaying = true;
      sinkPlayerStatus();
    } catch (err) {
      throw Exception(err);
    }
  }

  stop() {
    try {
      stream.stop();
      isPlaying = false;
      playerStatus.add(false);
    } catch (err) {
      throw Exception(err);
    }
  }

  playPause() {
    try {
      if (isPlaying) {
        stream.pause();
        isPlaying = false;
        sinkPlayerStatus();
      } else {
        stream.resume();
        isPlaying = true;
        sinkPlayerStatus();
      }
    } catch (err) {
      throw Exception(err);
    }
  }
}`

And this is the stream url that i'm trying to use.

[http://192.99.32.79:9972/stream](url)
