### ISSUE TITLE
Not working on Chrome

### ISSUE THREAD

**Issue by TheChileanKink** [tcronis/url_audio_stream#4]
Hello! Thanks for your amazing work. I'm using an express node js server to send a stream of audio. It works like a charm on IOS, but im testing on Web since the Web tag is in the pub.dart website, and I can't hear anything. Any ideas why it's not working?

**Comment by tcronis** [comment]
I'm so sorry, I didn't know it was tagged as Web. That is an oversight issue on my part, I built this only for iOS and Android purposes. It's possible in the future that I could release a version for Web, but as of now I haven't. I'm sorry again.

**Comment by TheChileanKink** [comment]
Aight! Thanks Tho:)
